main:
    host: 'localhost'
    user: 'user'
    password: 'password'
    port: 443
    ignore_ssl: True
    interval: 300
    log: INFO
    shorter_names_regex: '\.some\.domain\.name'
    host_match_regex: '.*buildingblock-xy.*'
    ignore_match_regex: '^testvmware.*'
    vm_metrics:
    - 'cpu.usage.average'
    - 'cpu.usagemhz.average'
    - 'cpu.ready.summation'
    - 'mem.usage.average'
    - 'mem.swapinRate.average'
    - 'mem.swapoutRate.average'
    - 'mem.vmmemctl.average'
    - 'mem.consumed.average'
    - 'mem.overhead.average'
    - 'disk.usage.average'
